project_id = "wbcsmkmtteabatakmhlz"

[functions.delete-expired-files]
verify_jwt = false

[functions.paddle-webhook]
verify_jwt = false

[functions.create-paddle-checkout]
verify_jwt = true

[functions.stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = true
